name: up_todo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  get_it: ^9.2.1
  go_router: ^17.1.0
  flutter_bloc: ^9.1.1
  cupertino_native_better: ^1.3.4
  lottie: ^3.3.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  cloud_firestore: ^6.1.2
  equatable: ^2.0.8
  either_dart: ^1.0.0
  logger: ^2.6.2
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:  
  android: true
  ios: true
  image_path: "assets/images/uptodo_logo.png" 

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Thin.ttf


